version: '3.6'

services:
  consul:
    build:
      context: ./consul
      dockerfile: Dockerfile
    ports:
      - "8500:8500"
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1 -config-file=/consul/config/config.hcl
    volumes:
      - "./consul/data:/consul/data"

  vault:
    build:
      context: ./vault
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    volumes:
      - "./vault/policies:/vault/policies"
      - "./vault/logs:/vault/logs"
    environment:
      - "VAULT_ADDR=http://127.0.0.1:8200"
    command: server -config=/vault/config/config.hcl
    cap_add:
      - "IPC_LOCK"
    depends_on:
      - consul
